[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.148.2"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/index.json"
  to = "/index.json"
  status = 200

[[headers]]
  for = "/contact/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
